version: '3'
services:
  chat-backend:
    build:
      context: ./chat-backend
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017/todo_db
    command: ["sh", "-c", "go mod tidy && go run main.go"]
  chat-frontend:
    build:
      context: ./chat-frontend
    container_name: chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      - chat-backend
  nginx:
    depends_on:
      - chat-frontend
      - chat-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

volumes:
  mongo_data:
